server:
  port: 8082

spring:
  application:
    name: book-catalog-service
  datasource:
    url: jdbc:postgresql://postgres:5432/bookstore_catalog
    username: ${DB_USERNAME:bookstore_user}
    password: ${DB_PASSWORD:bookstore_pass}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/catalog
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

logging:
  file:
    name: logs/book-catalog-service.log