spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_catalog_db
    username: bookstore
    password: bookstore123
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.bookstore.catalog: DEBUG
    org.springframework.cloud: DEBUG
    org.hibernate.SQL: DEBUG
