spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_dev
    username: ${DB_USERNAME:bookstore_user}
    password: ${DB_PASSWORD:bookstore_password}

logging:
  level:
    com.bookstore: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE